### ISSUE TITLE
Motion to grant governance of mdast-util-from-quill-delta

### ISSUE THREAD

**Issue by ChristianMurphy** [syntax-tree/governance#1]
process details at: https://github.com/unifiedjs/collective/blob/master/organizations.md#motion-to-grant-governance

**Project name**: mdast-util-from-quill-delta
**GitHub URL**: https://github.com/ChristianMurphy/mdast-util-from-quill-delta
**Overview**: This project allows using <https://quilljs.com> as a what you see is what you get (WYSIWYG) editor for remark.
It does this by converting [Quill's internal delta format](https://quilljs.com/docs/delta/) into a [markdown AST (mdast)](https://github.com/syntax-tree/mdast).
**Technology**:
* [quill-delta](https://github.com/quilljs/delta) for typings and utilities to manipulate Quill content
* [unist-builder](https://github.com/syntax-tree/unist-builder) to build unist/mdast trees
* [typescript](https://www.typescriptlang.org/) for type checking
* [ava](https://github.com/avajs/ava) for unit testing
* [nyc](https://github.com/istanbuljs/nyc) for test coverage measuring
* [xo](https://github.com/xojs/xo), [prettier](https://github.com/prettier/prettier), and [remark-preset-wooorm](https://github.com/wooorm/remark-preset-wooorm) for code style and formatting

**Comment by wooorm** [comment]
Nice! Btw, As a member you are [free to create a project directly](https://github.com/unifiedjs/collective/blob/master/organizations.md#management). If you are a user or contributor, you can use a motion to receive more rights (write rights).

I suggest adding a readme, and to make [this error message clearer](https://github.com/ChristianMurphy/mdast-util-from-quill-delta/blob/05f962c7af97158438972eb7dd80ca2d8888b59b/src/index.ts#L11), something about that it is undefined instead of unknown?

Note for me: add motion templates in governance repos!

**Comment by ChristianMurphy** [comment]
> As a member you are free to create a project directly. If you are a user or contributor, you can use a motion to receive more rights (write rights).

Good to know, transferring repo now.

> I suggest adding a readme, and to make this error message clearer, something about that it is undefined instead of unknown?

will do

**Comment by wooorm** [comment]
Nice! ✨
